### ISSUE TITLE
Improve headless backends.

### ISSUE THREAD

**Issue by goddessfreya** [rust-windowing/glutin#1106]
Targets for 0.21:
- [x] Linux | Wayland | EGL | PBuffer
- [x] Linux | Wayland | EGL | Surfaceless
- [x] Linux | X11 | EGL | PBuffer
- [x] Linux | X11 | EGL | Surfaceless
- [x] Linux | X11 | GLX | PBuffer

Others:
- [x] Linux | OSMesa
- [ ] Windows | EGL | Surfaceless
- [ ] Windows | WGL | PBuffer
- [x] Windows | EGL | PBuffer

**Comment by ZeGentzy** [comment]
Targets for 0.21 have been met!
